<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="unittest.loader._FailedTest-20200817185738" tests="1" file="unittest/loader.py" time="0.004" timestamp="2020-08-17T18:57:38" failures="0" errors="1" skipped="0">
	<testcase classname="unittest.loader._FailedTest" name="renewbookform" time="0.004" timestamp="2020-08-17T18:57:38" file="/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/loader.py" line="33">
		<error type="ImportError" message="Failed to import test module: renewbookform
Traceback (most recent call last):
  File &quot;/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/loader.py&quot;, line 154, in loadTestsFromName
    module = __import__(module_name)
ModuleNotFoundError: No module named 'renewbookform'
"><![CDATA[ImportError: Failed to import test module: renewbookform
Traceback (most recent call last):
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
ModuleNotFoundError: No module named 'renewbookform'

]]></error>
	</testcase>
</testsuite>
